name: ZMK Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install west
          west init -l app
          west update
          west zephyr-export

      - name: Build ZMK firmware
        run: |
          west build -d build/<nice_nano_v2> -b <strugglestick> app

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: zmk-firmware
          path: build/<nice_nano_v2>/zephyr/zmk.uf2
          
    
